using System.Windows;

namespace AnakinRaW.CommonUtilities.Wpf.Themes.Colors;

public class CommonControlsColors
{
    public static ComponentResourceKey ButtonBackground { get; } = new(typeof(CommonControlsColors), nameof(ButtonBackground));
    public static ComponentResourceKey ButtonBorder { get; } = new(typeof(CommonControlsColors), nameof(ButtonBorder));
    public static ComponentResourceKey ButtonText { get; } = new(typeof(CommonControlsColors), nameof(ButtonText));
    public static ComponentResourceKey ButtonDefaultBackground { get; } = new(typeof(CommonControlsColors), nameof(ButtonDefaultBackground));
    public static ComponentResourceKey ButtonDefaultBorder { get; } = new(typeof(CommonControlsColors), nameof(ButtonDefaultBorder));
    public static ComponentResourceKey ButtonDefaultText { get; } = new(typeof(CommonControlsColors), nameof(ButtonDefaultText));
    public static ComponentResourceKey ButtonFocusedBackground { get; } = new(typeof(CommonControlsColors), nameof(ButtonFocusedBackground));
    public static ComponentResourceKey ButtonFocusedBorder { get; } = new(typeof(CommonControlsColors), nameof(ButtonFocusedBorder));
    public static ComponentResourceKey ButtonFocusedText { get; } = new(typeof(CommonControlsColors), nameof(ButtonFocusedText));
    public static ComponentResourceKey ButtonHoverBackground { get; } = new(typeof(CommonControlsColors), nameof(ButtonHoverBackground));
    public static ComponentResourceKey ButtonHoverBorder { get; } = new(typeof(CommonControlsColors), nameof(ButtonHoverBorder));
    public static ComponentResourceKey ButtonHoverText { get; } = new(typeof(CommonControlsColors), nameof(ButtonHoverText));
    public static ComponentResourceKey ButtonPressedBackground { get; } = new(typeof(CommonControlsColors), nameof(ButtonPressedBackground));
    public static ComponentResourceKey ButtonPressedBorder { get; } = new(typeof(CommonControlsColors), nameof(ButtonPressedBorder));
    public static ComponentResourceKey ButtonPressedText { get; } = new(typeof(CommonControlsColors), nameof(ButtonPressedText));
    public static ComponentResourceKey ButtonDisabledBackground { get; } = new(typeof(CommonControlsColors), nameof(ButtonDisabledBackground));
    public static ComponentResourceKey ButtonDisabledBorder { get; } = new(typeof(CommonControlsColors), nameof(ButtonDisabledBorder));
    public static ComponentResourceKey ButtonDisabledText { get; } = new(typeof(CommonControlsColors), nameof(ButtonDisabledText));

    public static ComponentResourceKey CheckBoxBackground { get; } = new(typeof(CommonControlsColors), nameof(CheckBoxBackground));
    public static ComponentResourceKey CheckBoxBorder { get; } = new(typeof(CommonControlsColors), nameof(CheckBoxBorder));
    public static ComponentResourceKey CheckBoxGlyph { get; } = new(typeof(CommonControlsColors), nameof(CheckBoxGlyph));
    public static ComponentResourceKey CheckBoxText { get; } = new(typeof(CommonControlsColors), nameof(CheckBoxText));
    public static ComponentResourceKey CheckBoxBackgroundHover { get; } = new(typeof(CommonControlsColors), nameof(CheckBoxBackgroundHover));
    public static ComponentResourceKey CheckBoxBorderHover { get; } = new(typeof(CommonControlsColors), nameof(CheckBoxBorderHover));
    public static ComponentResourceKey CheckBoxGlyphHover { get; } = new(typeof(CommonControlsColors), nameof(CheckBoxGlyphHover));
    public static ComponentResourceKey CheckBoxTextHover { get; } = new(typeof(CommonControlsColors), nameof(CheckBoxTextHover));
    public static ComponentResourceKey CheckBoxBackgroundDown { get; } = new(typeof(CommonControlsColors), nameof(CheckBoxBackgroundDown));
    public static ComponentResourceKey CheckBoxBorderDown { get; } = new(typeof(CommonControlsColors), nameof(CheckBoxBorderDown));
    public static ComponentResourceKey CheckBoxGlyphDown { get; } = new(typeof(CommonControlsColors), nameof(CheckBoxGlyphDown));
    public static ComponentResourceKey CheckBoxTextDown { get; } = new(typeof(CommonControlsColors), nameof(CheckBoxTextDown));
    public static ComponentResourceKey CheckBoxBackgroundDisabled { get; } = new(typeof(CommonControlsColors), nameof(CheckBoxBackgroundDisabled));
    public static ComponentResourceKey CheckBoxBorderDisabled { get; } = new(typeof(CommonControlsColors), nameof(CheckBoxBorderDisabled));
    public static ComponentResourceKey CheckBoxGlyphDisabled { get; } = new(typeof(CommonControlsColors), nameof(CheckBoxGlyphDisabled));
    public static ComponentResourceKey CheckBoxTextDisabled { get; } = new(typeof(CommonControlsColors), nameof(CheckBoxTextDisabled));

    public static ComponentResourceKey TreeViewBackground { get; } = new(typeof(CommonControlsColors), nameof(TreeViewBackground));
    public static ComponentResourceKey TreeViewBorder { get; } = new(typeof(CommonControlsColors), nameof(TreeViewBorder));
    public static ComponentResourceKey TreeViewText { get; } = new(typeof(CommonControlsColors), nameof(TreeViewText));
    public static ComponentResourceKey TreeViewSelectedText { get; } = new(typeof(CommonControlsColors), nameof(TreeViewSelectedText));
    public static ComponentResourceKey TreeViewInactiveText { get; } = new(typeof(CommonControlsColors), nameof(TreeViewInactiveText));
    public static ComponentResourceKey TreeFocusBorder { get; } = new(typeof(CommonControlsColors), nameof(TreeFocusBorder));
    public static ComponentResourceKey TreeExpander { get; } = new(typeof(CommonControlsColors), nameof(TreeExpander));
    public static ComponentResourceKey TreeExpanderHover { get; } = new(typeof(CommonControlsColors), nameof(TreeExpanderHover));
    public static ComponentResourceKey TreeExpanderSelected { get; } = new(typeof(CommonControlsColors), nameof(TreeExpanderSelected));
    public static ComponentResourceKey TreeExpanderSelectedHover { get; } = new(typeof(CommonControlsColors), nameof(TreeExpanderSelectedHover));
    public static ComponentResourceKey TreeExpanderInactive { get; } = new(typeof(CommonControlsColors), nameof(TreeExpanderInactive));
    public static ComponentResourceKey TreeExpanderInactiveHover { get; } = new(typeof(CommonControlsColors), nameof(TreeExpanderInactiveHover));
    public static ComponentResourceKey TreeItemHover { get; } = new(typeof(CommonControlsColors), nameof(TreeItemHover));
    public static ComponentResourceKey TreeItemSelectedBackground { get; } = new(typeof(CommonControlsColors), nameof(TreeItemSelectedBackground));
    public static ComponentResourceKey TreeItemInactiveBackground { get; } = new(typeof(CommonControlsColors), nameof(TreeItemInactiveBackground));
   
    public static ComponentResourceKey ScrollBarArrowBackground { get; } = new(typeof(CommonControlsColors), nameof(ScrollBarArrowBackground));
    public static ComponentResourceKey ScrollBarArrowDisabledBackground { get; } = new(typeof(CommonControlsColors), nameof(ScrollBarArrowDisabledBackground));
    public static ComponentResourceKey ScrollBarArrowGlyph { get; } = new(typeof(CommonControlsColors), nameof(ScrollBarArrowGlyph));
    public static ComponentResourceKey ScrollBarArrowGlyphDisabled { get; } = new(typeof(CommonControlsColors), nameof(ScrollBarArrowGlyphDisabled));
    public static ComponentResourceKey ScrollBarArrowGlyphMouseOver { get; } = new(typeof(CommonControlsColors), nameof(ScrollBarArrowGlyphMouseOver));
    public static ComponentResourceKey ScrollBarArrowGlyphPressed { get; } = new(typeof(CommonControlsColors), nameof(ScrollBarArrowGlyphPressed));
    public static ComponentResourceKey ScrollBarArrowMouseOverBackground { get; } = new(typeof(CommonControlsColors), nameof(ScrollBarArrowMouseOverBackground));
    public static ComponentResourceKey ScrollBarArrowPressedBackground { get; } = new(typeof(CommonControlsColors), nameof(ScrollBarArrowPressedBackground));
    public static ComponentResourceKey ScrollBarBackground { get; } = new(typeof(CommonControlsColors), nameof(ScrollBarBackground));
    public static ComponentResourceKey ScrollBarBorder { get; } = new(typeof(CommonControlsColors), nameof(ScrollBarBorder));
    public static ComponentResourceKey ScrollBarDisabledBackground { get; } = new(typeof(CommonControlsColors), nameof(ScrollBarDisabledBackground));
    public static ComponentResourceKey ScrollBarThumbBackground { get; } = new(typeof(CommonControlsColors), nameof(ScrollBarThumbBackground));
    public static ComponentResourceKey ScrollBarThumbBorder { get; } = new(typeof(CommonControlsColors), nameof(ScrollBarThumbBorder));
    public static ComponentResourceKey ScrollBarThumbDisabled { get; } = new(typeof(CommonControlsColors), nameof(ScrollBarThumbDisabled));
    public static ComponentResourceKey ScrollBarThumbGlyph { get; } = new(typeof(CommonControlsColors), nameof(ScrollBarThumbGlyph));
    public static ComponentResourceKey ScrollBarThumbGlyphMouseOverBorder { get; } = new(typeof(CommonControlsColors), nameof(ScrollBarThumbGlyphMouseOverBorder));
    public static ComponentResourceKey ScrollBarThumbGlyphPressedBorder { get; } = new(typeof(CommonControlsColors), nameof(ScrollBarThumbGlyphPressedBorder));
    public static ComponentResourceKey ScrollBarThumbMouseOverBackground { get; } = new(typeof(CommonControlsColors), nameof(ScrollBarThumbMouseOverBackground));
    public static ComponentResourceKey ScrollBarThumbMouseOverBorder { get; } = new(typeof(CommonControlsColors), nameof(ScrollBarThumbMouseOverBorder));
    public static ComponentResourceKey ScrollBarThumbPressedBackground { get; } = new(typeof(CommonControlsColors), nameof(ScrollBarThumbPressedBackground));
    public static ComponentResourceKey ScrollBarThumbPressedBorder { get; } = new(typeof(CommonControlsColors), nameof(ScrollBarThumbPressedBorder));
    public static ComponentResourceKey AutoHideResizeGrip { get; } = new(typeof(CommonControlsColors), nameof(AutoHideResizeGrip));

    public static ComponentResourceKey ComboBoxBackground { get; } = new(typeof(CommonControlsColors), nameof(ComboBoxBackground));
    public static ComponentResourceKey ComboBoxBorder { get; } = new(typeof(CommonControlsColors), nameof(ComboBoxBorder));
    public static ComponentResourceKey ComboBoxText { get; } = new(typeof(CommonControlsColors), nameof(ComboBoxText));
    public static ComponentResourceKey ComboBoxListBackground { get; } = new(typeof(CommonControlsColors), nameof(ComboBoxListBackground));
    public static ComponentResourceKey ComboBoxListBorder { get; } = new(typeof(CommonControlsColors), nameof(ComboBoxListBorder));
    public static ComponentResourceKey ComboBoxListShadow { get; } = new(typeof(CommonControlsColors), nameof(ComboBoxListShadow));
    public static ComponentResourceKey ComboBoxGlyph { get; } = new(typeof(CommonControlsColors), nameof(ComboBoxGlyph));
    public static ComponentResourceKey ComboBoxGlyphBackground { get; } = new(typeof(CommonControlsColors), nameof(ComboBoxGlyphBackground));
    public static ComponentResourceKey ComboBoxSeparator { get; } = new(typeof(CommonControlsColors), nameof(ComboBoxSeparator));
    public static ComponentResourceKey ComboBoxBackgroundFocused { get; } = new(typeof(CommonControlsColors), nameof(ComboBoxBackgroundFocused));
    public static ComponentResourceKey ComboBoxBorderFocused { get; } = new(typeof(CommonControlsColors), nameof(ComboBoxBorderFocused));
    public static ComponentResourceKey ComboBoxTextFocused { get; } = new(typeof(CommonControlsColors), nameof(ComboBoxTextFocused));
    public static ComponentResourceKey ComboBoxGlyphFocused { get; } = new(typeof(CommonControlsColors), nameof(ComboBoxGlyphFocused));
    public static ComponentResourceKey ComboBoxGlyphBackgroundFocused { get; } = new(typeof(CommonControlsColors), nameof(ComboBoxGlyphBackgroundFocused));
    public static ComponentResourceKey ComboBoxSeparatorFocused { get; } = new(typeof(CommonControlsColors), nameof(ComboBoxSeparatorFocused));
    public static ComponentResourceKey ComboBoxBackgroundHover { get; } = new(typeof(CommonControlsColors), nameof(ComboBoxBackgroundHover));
    public static ComponentResourceKey ComboBoxBorderHover { get; } = new(typeof(CommonControlsColors), nameof(ComboBoxBorderHover));
    public static ComponentResourceKey ComboBoxTextHover { get; } = new(typeof(CommonControlsColors), nameof(ComboBoxTextHover));
    public static ComponentResourceKey ComboBoxGlyphHover { get; } = new(typeof(CommonControlsColors), nameof(ComboBoxGlyphHover));
    public static ComponentResourceKey ComboBoxGlyphBackgroundHover { get; } = new(typeof(CommonControlsColors), nameof(ComboBoxGlyphBackgroundHover));
    public static ComponentResourceKey ComboBoxSeparatorHover { get; } = new(typeof(CommonControlsColors), nameof(ComboBoxSeparatorHover));
    public static ComponentResourceKey ComboBoxBackgroundPressed { get; } = new(typeof(CommonControlsColors), nameof(ComboBoxBackgroundPressed));
    public static ComponentResourceKey ComboBoxBorderPressed { get; } = new(typeof(CommonControlsColors), nameof(ComboBoxBorderPressed));
    public static ComponentResourceKey ComboBoxTextPressed { get; } = new(typeof(CommonControlsColors), nameof(ComboBoxTextPressed));
    public static ComponentResourceKey ComboBoxGlyphBackgroundPressed { get; } = new(typeof(CommonControlsColors), nameof(ComboBoxGlyphBackgroundPressed));
    public static ComponentResourceKey ComboBoxSeparatorPressed { get; } = new(typeof(CommonControlsColors), nameof(ComboBoxSeparatorPressed));
    public static ComponentResourceKey ComboBoxGlyphPressed { get; } = new(typeof(CommonControlsColors), nameof(ComboBoxGlyphPressed));
    public static ComponentResourceKey ComboBoxBackgroundDisabled { get; } = new(typeof(CommonControlsColors), nameof(ComboBoxBackgroundDisabled));
    public static ComponentResourceKey ComboBoxBorderDisabled { get; } = new(typeof(CommonControlsColors), nameof(ComboBoxBorderDisabled));
    public static ComponentResourceKey ComboBoxTextDisabled { get; } = new(typeof(CommonControlsColors), nameof(ComboBoxTextDisabled));
    public static ComponentResourceKey ComboBoxGlyphDisabled { get; } = new(typeof(CommonControlsColors), nameof(ComboBoxGlyphDisabled));
    public static ComponentResourceKey ComboBoxGlyphBackgroundDisabled { get; } = new(typeof(CommonControlsColors), nameof(ComboBoxGlyphBackgroundDisabled));
    public static ComponentResourceKey ComboBoxTextInputSelection { get; } = new(typeof(CommonControlsColors), nameof(ComboBoxTextInputSelection));
    public static ComponentResourceKey ComboBoxListItemText { get; } = new(typeof(CommonControlsColors), nameof(ComboBoxListItemText));
    public static ComponentResourceKey ComboBoxListItemBackgroundHover { get; } = new(typeof(CommonControlsColors), nameof(ComboBoxListItemBackgroundHover));
    public static ComponentResourceKey ComboBoxListItemBorderHover { get; } = new(typeof(CommonControlsColors), nameof(ComboBoxListItemBorderHover));
    public static ComponentResourceKey ComboBoxListItemTextHover { get; } = new(typeof(CommonControlsColors), nameof(ComboBoxListItemTextHover));


    public static ComponentResourceKey ProgressBarBackground { get; } = new(typeof(CommonControlsColors), nameof(ProgressBarBackground));
    public static ComponentResourceKey ProgressBarBorder { get; } = new(typeof(CommonControlsColors), nameof(ProgressBarBorder));
    public static ComponentResourceKey ProgressBarValue { get; } = new(typeof(CommonControlsColors), nameof(ProgressBarValue));
}